apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: dp-oppslag-arbeidssoker
    team: teamdagpenger
  name: dp-oppslag-arbeidssoker
  namespace: teamdagpenger
spec:
  image: {{ image }}
  liveness:
    path: /isalive
  readiness:
    path: /isready
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    max: 6
    min: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  secureLogs:
    enabled: true
  kafka:
    pool: {{kafka_pool}}
  webproxy: true
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: veilarbregistrering
          namespace: paw
      external:
        - host: {{ veilarbregistrering.ingress }}

