apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  annotations:
    zone: fss
  labels:
    app: dp-oppslag-arbeidssoker
    team: teamdagpenger
  name: dp-oppslag-arbeidssoker
  namespace: teamdagpenger
spec:
  image: {{ image }}
  liveness:
    path: /isalive
  readiness:
    path: /isready
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    max: 6
    min: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  secureLogs:
    enabled: true
  env:
    - name: KAFKA_PREFER_ON_PREM
      value: "true"
  vault:
    enabled: true
    paths:
      - kvPath: "serviceuser/data/dev/srvdp-arbeidssoker-o"
        mountPath: "/var/run/secrets/nais.io/service_user/"
  
