apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: dp-oppslag-arbeidssoker
    team: teamdagpenger
  name: dp-oppslag-arbeidssoker
  namespace: teamdagpenger
spec:
  image: "{{ image }}"
  startup:
    path: /isalive
    initialDelay: 10
    failureThreshold: 6
    periodSeconds: 5
    timeout: 1
  liveness:
    path: /isalive
    failureThreshold: 6
    periodSeconds: 10
  readiness:
    path: /isready
    failureThreshold: 3
    periodSeconds: 10
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    max: 2
    min: 2
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi
  secureLogs:
    enabled: true
  kafka:
    pool: "{{kafka_pool}}"
  webproxy: true
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
  env:
    - name: ARBEIDSSOKERREGISTERET_API_URL
      value: "{{arbeidssokerregisteret_url}}"
    - name: ARBEIDSSOKERREGISTERET_API_SCOPE
      value: "{{arbeidssokerregisteret_scope}}"
  accessPolicy:
    outbound:
      rules:
        - application: "{{arbeidssoekerregisteret.url}}"
          namespace: paw

